services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - db
    networks:
      - sonar_net
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/tc_order_db
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: secret
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
  db:
    image: 'postgres:latest'
    container_name: order-tech-challenge-db
    restart: always
    hostname: postgres
    environment:
      - 'POSTGRES_DB=tc_order_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
    networks:
      - sonar_net
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  sonar_data:
  sonar_logs:
  db:
    driver: local
networks:
  sonar_net:
    driver: bridge